// SPDX-License-Identifier: GPL-3.0-only
//
// Copyright (C) 2026 Gustavo Noronha Silva <gustavo@noronha.dev.br>

//! Generates `resources/emoji-table.txt` from Unicode's `emoji-test.txt` and CLDR's English
//! annotations. Run by hand when either ships a new release; see `README.md` for the fetch.
//!
//! The generator is the place where the data is checked: an entry whose skin-tone name does not
//! resolve to a base entry is a hard error, because the alternative is a picker that silently
//! drops emoji or shows tone variants as if they were separate characters.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::PathBuf;
use std::process::ExitCode;

use quick_xml::events::Event;
use quick_xml::{Reader, XmlVersion};

struct Entry {
    ch: String,
    name: String,
    group: usize,
    /// Skin-tone spellings of this entry, in file order.
    variants: Vec<String>,
}

fn main() -> ExitCode {
    let mut args = std::env::args_os().skip(1).map(PathBuf::from);
    let (Some(test), Some(annotations), Some(derived), Some(cldr), Some(out)) = (
        args.next(),
        args.next(),
        args.next(),
        args.next(),
        args.next(),
    ) else {
        eprintln!(
            "usage: emoji-table <emoji-test.txt> <cldr annotations en.xml> \
             <cldr annotationsDerived en.xml> <cldr version> <out.txt>"
        );
        return ExitCode::FAILURE;
    };
    // CLDR's own files carry `<version number="$Revision$"/>`, so the release is ours to state.
    let cldr = cldr.to_string_lossy().into_owned();

    let test = match std::fs::read_to_string(&test) {
        Ok(text) => text,
        Err(err) => {
            eprintln!("{}: {err}", test.display());
            return ExitCode::FAILURE;
        }
    };

    let mut keywords = HashMap::new();
    for path in [&annotations, &derived] {
        if let Err(err) = read_annotations(path, &mut keywords) {
            eprintln!("{}: {err}", path.display());
            return ExitCode::FAILURE;
        }
    }

    let (version, groups, entries) = match parse_test(&test) {
        Ok(parsed) => parsed,
        Err(err) => {
            eprintln!("emoji-test.txt: {err}");
            return ExitCode::FAILURE;
        }
    };

    let mut text = String::new();
    let _ = writeln!(
        text,
        "# Emoji {version} / CLDR {cldr}. Generated by tools/emoji-table — do not edit."
    );
    let _ = writeln!(
        text,
        "# <group> lines open a group; entries are char, name, keywords (|), tone variants ( )."
    );
    // Unicode's license asks that the notice travel with derivative data files, and this file is
    // one — Unicode's names and order, CLDR's keywords.
    let _ = writeln!(
        text,
        "# Derived from Unicode emoji-test.txt and CLDR annotations."
    );
    let _ = writeln!(
        text,
        "# © Unicode, Inc. Licensed under the Unicode License v3 (SPDX: Unicode-3.0),"
    );
    let _ = writeln!(text, "# https://www.unicode.org/license.txt");
    let mut current = usize::MAX;
    for entry in &entries {
        if entry.group != current {
            current = entry.group;
            let _ = writeln!(text, "<{}>", groups[current]);
        }
        let kw = lookup(&keywords, &entry.ch).unwrap_or_default();
        let _ = writeln!(
            text,
            "{}\t{}\t{}\t{}",
            entry.ch,
            entry.name,
            kw,
            entry.variants.join(" ")
        );
    }

    if let Err(err) = std::fs::write(&out, &text) {
        eprintln!("{}: {err}", out.display());
        return ExitCode::FAILURE;
    }

    let toned = entries.iter().filter(|e| !e.variants.is_empty()).count();
    let unnamed = entries
        .iter()
        .filter(|e| lookup(&keywords, &e.ch).is_none())
        .count();
    eprintln!(
        "{} entries in {} groups, {toned} with skin tones, {unnamed} without CLDR keywords",
        entries.len(),
        groups.len(),
    );
    ExitCode::SUCCESS
}

/// CLDR keys its annotations by the sequence with every `U+FE0F` removed, so a fully-qualified
/// emoji misses unless the stripped spelling is tried too — that is 365 of 1914 entries, most of
/// the older ones, silently keyword-less.
fn lookup<'a>(keywords: &'a HashMap<String, String>, ch: &str) -> Option<&'a str> {
    if let Some(kw) = keywords.get(ch) {
        return Some(kw);
    }
    let stripped: String = ch.chars().filter(|c| *c != '\u{fe0f}').collect();
    keywords.get(&stripped).map(String::as_str)
}

/// Collect `cp -> keywords` from a CLDR annotations file, skipping the `type="tts"` names.
///
/// Multi-codepoint sequences appear with the sequence itself in `cp`, so no reassembly is needed.
fn read_annotations(
    path: &PathBuf,
    out: &mut HashMap<String, String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut reader = Reader::from_file(path)?;
    let mut buf = Vec::new();
    let mut pending: Option<String> = None;
    loop {
        match reader.read_event_into(&mut buf)? {
            Event::Start(tag) if tag.name().as_ref() == "annotation" => {
                let mut cp = None;
                let mut tts = false;
                for attr in tag.attributes() {
                    let attr = attr?;
                    match attr.key.as_ref() {
                        "cp" => {
                            cp = Some(attr.normalized_value(XmlVersion::Implicit1_0)?.into_owned())
                        }
                        "type" => tts = attr.normalized_value(XmlVersion::Implicit1_0)? == "tts",
                        _ => {}
                    }
                }
                pending = cp.filter(|_| !tts);
            }
            Event::Text(text) => {
                if let Some(cp) = pending.take() {
                    // CLDR separates keywords with " | "; keep that, minus the spaces.
                    let content = text.xml_content(XmlVersion::Implicit1_0);
                    let kw: Vec<_> = content
                        .split('|')
                        .map(str::trim)
                        .filter(|s| !s.is_empty())
                        .collect();
                    if !kw.is_empty() {
                        out.insert(cp, kw.join("|"));
                    }
                }
            }
            Event::End(tag) if tag.name().as_ref() == "annotation" => pending = None,
            Event::Eof => return Ok(()),
            _ => {}
        }
        buf.clear();
    }
}

/// Parse `emoji-test.txt` into groups and fully-qualified entries, folding skin-tone spellings
/// into the entry they vary.
fn parse_test(text: &str) -> Result<(String, Vec<String>, Vec<Entry>), String> {
    let mut version = String::from("unknown");
    let mut groups: Vec<String> = Vec::new();
    let mut entries: Vec<Entry> = Vec::new();
    let mut by_name: HashMap<String, usize> = HashMap::new();
    let mut collapsed: Vec<String> = Vec::new();

    for line in text.lines() {
        if let Some(group) = line.strip_prefix("# group: ") {
            groups.push(group.trim().to_owned());
            continue;
        }
        if let Some(v) = line.strip_prefix("# Version: ") {
            version = v.trim().to_owned();
            continue;
        }
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }

        let Some((codes, rest)) = line.split_once(';') else {
            continue;
        };
        let Some((status, comment)) = rest.split_once('#') else {
            continue;
        };
        if status.trim() != "fully-qualified" {
            continue;
        }

        let ch = codes
            .split_whitespace()
            .map(|code| {
                u32::from_str_radix(code, 16)
                    .ok()
                    .and_then(char::from_u32)
                    .ok_or_else(|| format!("bad code point {code:?}"))
            })
            .collect::<Result<String, _>>()?;

        // "<emoji> E<version> <name>" — the name is everything past the emoji version.
        let mut fields = comment.trim().splitn(3, ' ');
        let (_, _, Some(name)) = (fields.next(), fields.next(), fields.next()) else {
            return Err(format!("no name in {comment:?}"));
        };
        let name = name.trim().to_owned();

        if let Some(base) = base_name(&name) {
            // Unicode gives some sequences *only* toned spellings: there is no
            // "kiss: person, person", just "kiss" and its 25 toned couples. Those fold into the
            // head instead, which is the emoji a picker shows and the one the tones vary.
            let at = by_name.get(&base).or_else(|| {
                let head = base.split_once(": ")?.0;
                collapsed.push(name.clone());
                by_name.get(head)
            });
            let Some(&at) = at else {
                return Err(format!("{name:?} varies {base:?}, which is not an entry"));
            };
            entries[at].variants.push(ch);
            continue;
        }

        let group = groups
            .len()
            .checked_sub(1)
            .ok_or_else(|| format!("{name:?} precedes any group"))?;
        by_name.insert(name.clone(), entries.len());
        entries.push(Entry {
            ch,
            name,
            group,
            variants: Vec::new(),
        });
    }

    if entries.is_empty() {
        return Err("no entries".to_owned());
    }
    if !collapsed.is_empty() {
        eprintln!(
            "{} toned spellings folded into a shorter base, e.g. {:?}",
            collapsed.len(),
            &collapsed[..collapsed.len().min(3)]
        );
    }
    Ok((version, groups, entries))
}

/// The name of the entry a skin-tone spelling varies, or `None` when the name is a base.
///
/// Tone parts sit in the comma-separated list after the colon and can be interleaved with parts
/// that are *not* tones ("couple with heart: woman, man, dark skin tone, light skin tone"), so the
/// base is the name with only the tone parts removed — not the text before the colon.
fn base_name(name: &str) -> Option<String> {
    let (head, tail) = name.split_once(": ")?;
    let kept: Vec<_> = tail
        .split(", ")
        .filter(|part| !part.ends_with("skin tone"))
        .collect();
    if kept.len() == tail.split(", ").count() {
        return None;
    }
    Some(if kept.is_empty() {
        head.to_owned()
    } else {
        format!("{head}: {}", kept.join(", "))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tone_parts_are_stripped_wherever_they_sit() {
        assert_eq!(base_name("waving hand"), None);
        assert_eq!(base_name("person: beard"), None);
        assert_eq!(
            base_name("waving hand: light skin tone").as_deref(),
            Some("waving hand")
        );
        assert_eq!(
            base_name("couple with heart: woman, man, dark skin tone, light skin tone").as_deref(),
            Some("couple with heart: woman, man")
        );
        assert_eq!(
            base_name("man: light skin tone, beard").as_deref(),
            Some("man: beard")
        );
    }
}
